{% set name = "python-stratify" %}
{% set version = "0.1a2" %}
{% set sha256 = "60354ac1e083452deaa8c32fc58cb0873479ed18092b05e9d6c1f7b3ce921ada" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: python-stratify-{{ version }}.tar.gz
  url: https://github.com/SciTools-incubator/python-stratify/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - numpy x.x
    - cython
  run:
    - python
    - numpy x.x

test:
  imports:
    - stratify

about:
  home: https://github.com/SciTools-incubator/python-stratify
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Vectorized interpolators that are especially useful for Nd vertical interpolation/stratification of atmospheric and oceanographic datasets.'

extra:
  recipe-maintainers:
    - bjlittle
    - cpelley
    - lbdreyer
    - ocefpaf
    - pelson
