appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: aw9Wx19b+k11Y/g3QAA54fTUBIMcexx1Zu2afuhRTL3PpsFpMxIQu2YILuK6VpwoCj/dDWpXVZiov1fpEkZBItOmyyCAA0pxP33OxmcKpBrzDXON4el+9hfV8pRuCgoYGF5F3j4vr+vOu4Mqoonb1b4MofS52p26w7Kt7u33YVerix3i+DOUft3sVPIJVqA2z8lIQRyd944XRO74kWW1F26NI/+SzV79DDGdco5OxFpmL75QvhT4aana0YfM+VNFHgJDJLRItsTtOOqunf8u2jSx8Cg8sjQq+TGhFvP3goSUBK4cyu+sNz575lFBuEWt1rbl3BFxTAfcrhUq8YWReOtOczkv4SwXRSe9pBdlrm7MlY07Zucb3VPHeVeVy8zGFxKBKK7Xz4K+Nd1AQ8wIXILs288+BQXBJNJgfKHBRmh7wdoHT7s1WSRFtCNHHdT4pTq4sxLToz0snHL/HvgDZ4owgJGky4iVmKEHWzIQIbBs0siA0+YXHo7WoMdvLtq6/ziLoWu9LfSnMsNIcP9daNCwNzP33/JvuqXP1hqY5knTJtWBjpTy8150JFi174B/u9zx4hKR1anOexdjMeL4g/lCK/u+kwHOWc/AEPJljnBlTCfUgO7sYamZC1r7NkP4TMWavinJpPkfdh3hZsox21GVjqP1vS7FrZTGWW07iNU=}
provider:
  win: azure
