travis:
  secure:
    BINSTAR_TOKEN: fV/OEQef8hkVPSZZolBqvklsoYgOKtvVsvrHLgRHR0loLEq2L0P43upu9DuEM0eygEh3GKLUdenWrFJvZlhjIyIADV+k0vyHwXRod+rPIiDOaWURYy2erG63NUE495+2ZvnvTl+vu1eItJKFTsts8xLG1XfKaE83NASLOipeWDerAiBf9TqbLN6J6GyTd30aXZk0/nx7/s8FOe//Ih1VJesSY/aqu/l9MFtozVObLkZX13RKiPbXNS6iPiXaCDni2EIleGier5gU9qQhu+niyId8dL3DJug2IU3/4ukX65rI9Uc/DsaYJy6my2pBiVG/vU2dh/T+fK6a1gPk4V7JJVvvUShg4kv2JeYF1fHIQfHsuhaapwk229cXgFvZYcig+udWi3D7HzyMMKxN/eR3At2Ek2xVRSjQwD3W/JOPdTn6HkGCsJcqk8ftRhMibrw7iBzXbp9HfdD7gwIoA3oL1B2sis+ZPd2IxYhkuKpwRvolKbrcPib1z8zj8nDmv4FQ6FGvP7jOQpiuQPsA6KYEdQhcbSVV0e41TYl9dDW1w/smetVu82kFGG/Smdg4WlQMs+kWepuv58UunP6cHsaIKVv6c6Lg762jWolC5lACFMfokqlkexIso92xA9iHBiDO0h6Bot3cPErvQGK7UiMZ2USjZMNSaN9hPNEdeFLY734=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
